---
version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - funlen
    - gocognit
    - gocyclo
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - tagalign
    - testpackage
    - varnamelen
    - whitespace
    - wsl
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - exhaustruct
          - forcetypeassert
          - wrapcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

run:
  tests: true
  timeout: 100s

severity:
  default: error
